language: rust
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      rust: stable
    - os: osx
      osx_image: xcode12.2 # request macOS 10.15.7
      rust: stable
  allow_failures:
    - os: linux

compiler:
  - clang

services:
  - docker

env:
  global:
    - PROTOBUF_DIR="$HOME/protobuf"
    - PROTOBUF_VERSION=3.9.1
    - LCOV_VERSION=1.13

addons:
  apt:
    update: true
    packages:
      - libzmq3-dev
#      - build-essential
#      - autoconf
#      - automake
#      - libtool
#      - curl
#      - make
#      - unzip
#      - pkg-config
#      - wget
#      - libc++-dev
#      - libc++abi-dev
#      - jq
#      - python3-pip
  homebrew:
    packages:
      - zmq
#      - autoconf
#      - automake
#      - libtool
#      - build-essential
#      - unzip
#      - pkg-config
#      - wget

cache:
  directories:
    - $PROTOBUF_DIR

# Avoid the double-build in travis. With this option it will perform a rebase on master of your PR then build that only
branches:
  only:
    - "master"

install:
  - ./common/scripts/travis/travis-install.sh
  - rustup --quiet component add clippy

script:
  - ./scripts/build.sh -bDebug -t -j2 && ./tests/simple/test-simple.sh && cargo clippy && cargo test

after_success:
  - ./scripts/travis/upload-codecov.sh
  - ./scripts/travis/docker-build.sh

after_failure:
  - echo "=========CMakeOutput.log===================" && cat $HOME/build/andrewdavidmackenzie/anna/build/CMakeFiles/CMakeOutput.log
  - echo "=========CMakeError.log===================" && cat $HOME/build/andrewdavidmackenzie/anna/build/CMakeFiles/CMakeError.log