[book]
title = "The 'anna' book"
authors = ["Andrew Mackenzie"]
description = "A guide to 'anna'"
src = "."

[build]
build-dir = "target"
create-missing = false
use-default-preprocessors = false

[output.html]
[preprocessor.links]