[workspace]
members = [
    "clients/rust",
    "server/rust/server-common",
    "server/rust/anna-monitor",
    "server/rust/anna-hashring",
    "server/rust/anna-lattice",
    "server/rust/anna-kvs",
    "server/rust/anna-embedded",
    "server/rust/anna-route",
]
default-members = ["clients/rust"]
