//  Copyright 2019 U.C. Berkeley RISE Lab
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: kvs.proto

package kvs

import (
	shared "github.com/andrewdavidmackenzie/anna/clients/go/annalib/proto/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An enum to differentiate between different KVS requests.
type RequestType int32

const (
	// A default type to capture unspecified requests.
	RequestType_RT_UNSPECIFIED RequestType = 0
	// A request to retrieve data from the KVS.
	RequestType_GET RequestType = 1
	// A request to put data into the KVS.
	RequestType_PUT RequestType = 2
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "RT_UNSPECIFIED",
		1: "GET",
		2: "PUT",
	}
	RequestType_value = map[string]int32{
		"RT_UNSPECIFIED": 0,
		"GET":            1,
		"PUT":            2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_kvs_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_kvs_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{0}
}

type LatticeType int32

const (
	// No lattice type specified
	LatticeType_NONE LatticeType = 0
	// Last-writer wins lattice
	LatticeType_LWW LatticeType = 1
	// Unordered set lattice
	LatticeType_SET LatticeType = 2
	// Single-key causal lattice
	LatticeType_SINGLE_CAUSAL LatticeType = 3
	// Multi-key causal lattice
	LatticeType_MULTI_CAUSAL LatticeType = 4
	// Ordered-set lattice
	LatticeType_ORDERED_SET LatticeType = 5
	// Priority lattice
	LatticeType_PRIORITY LatticeType = 6
	// Last-writer-wins set: a set of values where the entire set is replaced
	// on each write (timestamp-based), rather than merged via union.
	LatticeType_LWW_SET LatticeType = 7
	// Union scalar: each PUT appends a string fragment. The merge is set-union
	// of all fragments, displayed concatenated in sorted order. Useful for
	// append-only logs, sensor readings, or accumulating text.
	LatticeType_UNION_SCALAR LatticeType = 8
	// Last-writer-wins ordered set: an ordered collection where the entire
	// list is replaced on each write (timestamp-based), preserving insertion
	// order. Like LWW_SET but ordered.
	LatticeType_LWW_ORDERED_SET LatticeType = 9
	// Priority set: a set of values where the entire set with the lowest
	// priority wins. The value field in PriorityValue holds a serialized
	// SetValue.
	LatticeType_PRIORITY_SET LatticeType = 10
	// Priority ordered set: like PRIORITY_SET but preserves insertion order.
	LatticeType_PRIORITY_ORDERED_SET LatticeType = 11
	// Single-key causal set: a set of values with single-key causal
	// consistency. Each values entry in SingleKeyCausalValue holds a
	// serialized SetValue.
	LatticeType_CAUSAL_SET LatticeType = 12
	// Single-key causal ordered set: like CAUSAL_SET but ordered.
	LatticeType_CAUSAL_ORDERED_SET LatticeType = 13
	// Multi-key causal set: a set of values with multi-key causal
	// consistency and cross-key dependencies. Each values entry in
	// MultiKeyCausalValue holds a serialized SetValue.
	LatticeType_MULTI_CAUSAL_SET LatticeType = 14
	// Multi-key causal ordered set: like MULTI_CAUSAL_SET but ordered.
	LatticeType_MULTI_CAUSAL_ORDERED_SET LatticeType = 15
)

// Enum value maps for LatticeType.
var (
	LatticeType_name = map[int32]string{
		0:  "NONE",
		1:  "LWW",
		2:  "SET",
		3:  "SINGLE_CAUSAL",
		4:  "MULTI_CAUSAL",
		5:  "ORDERED_SET",
		6:  "PRIORITY",
		7:  "LWW_SET",
		8:  "UNION_SCALAR",
		9:  "LWW_ORDERED_SET",
		10: "PRIORITY_SET",
		11: "PRIORITY_ORDERED_SET",
		12: "CAUSAL_SET",
		13: "CAUSAL_ORDERED_SET",
		14: "MULTI_CAUSAL_SET",
		15: "MULTI_CAUSAL_ORDERED_SET",
	}
	LatticeType_value = map[string]int32{
		"NONE":                     0,
		"LWW":                      1,
		"SET":                      2,
		"SINGLE_CAUSAL":            3,
		"MULTI_CAUSAL":             4,
		"ORDERED_SET":              5,
		"PRIORITY":                 6,
		"LWW_SET":                  7,
		"UNION_SCALAR":             8,
		"LWW_ORDERED_SET":          9,
		"PRIORITY_SET":             10,
		"PRIORITY_ORDERED_SET":     11,
		"CAUSAL_SET":               12,
		"CAUSAL_ORDERED_SET":       13,
		"MULTI_CAUSAL_SET":         14,
		"MULTI_CAUSAL_ORDERED_SET": 15,
	}
)

func (x LatticeType) Enum() *LatticeType {
	p := new(LatticeType)
	*p = x
	return p
}

func (x LatticeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LatticeType) Descriptor() protoreflect.EnumDescriptor {
	return file_kvs_proto_enumTypes[1].Descriptor()
}

func (LatticeType) Type() protoreflect.EnumType {
	return &file_kvs_proto_enumTypes[1]
}

func (x LatticeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LatticeType.Descriptor instead.
func (LatticeType) EnumDescriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{1}
}

type AnnaError int32

const (
	// The request did not have an error.
	AnnaError_NO_ERROR AnnaError = 0
	// The requested key does not exist.
	AnnaError_KEY_DNE AnnaError = 1
	// The request was sent to the wrong thread, which is not responsible for the key.
	AnnaError_WRONG_THREAD AnnaError = 2
	// The request timed out.
	AnnaError_TIMEOUT AnnaError = 3
	// The lattice type was not correctly specified or conflicted with an existing key.
	AnnaError_LATTICE AnnaError = 4
	// This error is returned by the routing tier if no servers are in the cluster.
	AnnaError_NO_SERVERS AnnaError = 5
)

// Enum value maps for AnnaError.
var (
	AnnaError_name = map[int32]string{
		0: "NO_ERROR",
		1: "KEY_DNE",
		2: "WRONG_THREAD",
		3: "TIMEOUT",
		4: "LATTICE",
		5: "NO_SERVERS",
	}
	AnnaError_value = map[string]int32{
		"NO_ERROR":     0,
		"KEY_DNE":      1,
		"WRONG_THREAD": 2,
		"TIMEOUT":      3,
		"LATTICE":      4,
		"NO_SERVERS":   5,
	}
)

func (x AnnaError) Enum() *AnnaError {
	p := new(AnnaError)
	*p = x
	return p
}

func (x AnnaError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnaError) Descriptor() protoreflect.EnumDescriptor {
	return file_kvs_proto_enumTypes[2].Descriptor()
}

func (AnnaError) Type() protoreflect.EnumType {
	return &file_kvs_proto_enumTypes[2]
}

func (x AnnaError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnaError.Descriptor instead.
func (AnnaError) EnumDescriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{2}
}

// A protobuf to represent an individual key, both for requests and responses.
type KeyTuple struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key name for this request/response.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The lattice type for this key. Only required for server responses and PUT requests.
	LatticeType LatticeType `protobuf:"varint,2,opt,name=lattice_type,json=latticeType,proto3,enum=kvs.LatticeType" json:"lattice_type,omitempty"`
	// The error type specified by the server (see AnnaError).
	Error AnnaError `protobuf:"varint,3,opt,name=error,proto3,enum=kvs.AnnaError" json:"error,omitempty"`
	// The data associated with this key.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// The number of server addresses the client is aware of for a particular
	// key; used for DHT membership change optimization.
	AddressCacheSize uint32 `protobuf:"varint,5,opt,name=address_cache_size,json=addressCacheSize,proto3" json:"address_cache_size,omitempty"`
	// A boolean set by the server if the client's address_cache_size does not
	// match the metadata stored by the server.
	Invalidate    bool `protobuf:"varint,6,opt,name=invalidate,proto3" json:"invalidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyTuple) Reset() {
	*x = KeyTuple{}
	mi := &file_kvs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyTuple) ProtoMessage() {}

func (x *KeyTuple) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyTuple.ProtoReflect.Descriptor instead.
func (*KeyTuple) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{0}
}

func (x *KeyTuple) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyTuple) GetLatticeType() LatticeType {
	if x != nil {
		return x.LatticeType
	}
	return LatticeType_NONE
}

func (x *KeyTuple) GetError() AnnaError {
	if x != nil {
		return x.Error
	}
	return AnnaError_NO_ERROR
}

func (x *KeyTuple) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *KeyTuple) GetAddressCacheSize() uint32 {
	if x != nil {
		return x.AddressCacheSize
	}
	return 0
}

func (x *KeyTuple) GetInvalidate() bool {
	if x != nil {
		return x.Invalidate
	}
	return false
}

// An individual GET or PUT request; each request can batch multiple keys.
type KeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of this request (see RequestType).
	Type RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=kvs.RequestType" json:"type,omitempty"`
	// A list of KeyTuples batched in this request.
	Tuples []*KeyTuple `protobuf:"bytes,2,rep,name=tuples,proto3" json:"tuples,omitempty"`
	// The IP-port pair at which the client is waiting for the server's response.
	ResponseAddress string `protobuf:"bytes,3,opt,name=response_address,json=responseAddress,proto3" json:"response_address,omitempty"`
	// A client-specific ID used to match asynchronous requests with responses.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_kvs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{1}
}

func (x *KeyRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_RT_UNSPECIFIED
}

func (x *KeyRequest) GetTuples() []*KeyTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

func (x *KeyRequest) GetResponseAddress() string {
	if x != nil {
		return x.ResponseAddress
	}
	return ""
}

func (x *KeyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// A response to a KeyRequest.
type KeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of response being sent back to the client (see RequestType).
	Type RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=kvs.RequestType" json:"type,omitempty"`
	// The individual response pairs associated with this request. There is a
	// 1-to-1 mapping between these and the KeyTuples in the corresponding KeyRequest.
	Tuples []*KeyTuple `protobuf:"bytes,2,rep,name=tuples,proto3" json:"tuples,omitempty"`
	// The request_id specified in the corresponding KeyRequest. Used to associate asynchronous requests and responses.
	ResponseId string `protobuf:"bytes,3,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	// Any errors associated with the whole request. Individual tuple errors are
	// captured in the corresponding KeyTuple. This will only be set if the whole
	// request times out.
	Error         AnnaError `protobuf:"varint,4,opt,name=error,proto3,enum=kvs.AnnaError" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyResponse) Reset() {
	*x = KeyResponse{}
	mi := &file_kvs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponse) ProtoMessage() {}

func (x *KeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponse.ProtoReflect.Descriptor instead.
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{2}
}

func (x *KeyResponse) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_RT_UNSPECIFIED
}

func (x *KeyResponse) GetTuples() []*KeyTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

func (x *KeyResponse) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *KeyResponse) GetError() AnnaError {
	if x != nil {
		return x.Error
	}
	return AnnaError_NO_ERROR
}

// A request to the routing tier to retrieve server addresses corresponding to
// individual keys.
type KeyAddressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IP-port pair at which the client will await a response.
	ResponseAddress string `protobuf:"bytes,1,opt,name=response_address,json=responseAddress,proto3" json:"response_address,omitempty"`
	// The names of the requested keys.
	Keys []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// A unique ID used by the client to match asynchronous requests with responses.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAddressRequest) Reset() {
	*x = KeyAddressRequest{}
	mi := &file_kvs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAddressRequest) ProtoMessage() {}

func (x *KeyAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAddressRequest.ProtoReflect.Descriptor instead.
func (*KeyAddressRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{3}
}

func (x *KeyAddressRequest) GetResponseAddress() string {
	if x != nil {
		return x.ResponseAddress
	}
	return ""
}

func (x *KeyAddressRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeyAddressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// A 1-to-1 response from the routing tier for individual KeyAddressRequests.
type KeyAddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A batch of responses for individual keys.
	Addresses []*KeyAddressResponse_KeyAddress `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// An error reported by the routing tier. This should only ever be a timeout.
	Error AnnaError `protobuf:"varint,2,opt,name=error,proto3,enum=kvs.AnnaError" json:"error,omitempty"`
	// A unique ID used by the client to match asynchronous requests with responses.
	ResponseId    string `protobuf:"bytes,3,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAddressResponse) Reset() {
	*x = KeyAddressResponse{}
	mi := &file_kvs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAddressResponse) ProtoMessage() {}

func (x *KeyAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAddressResponse.ProtoReflect.Descriptor instead.
func (*KeyAddressResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{4}
}

func (x *KeyAddressResponse) GetAddresses() []*KeyAddressResponse_KeyAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *KeyAddressResponse) GetError() AnnaError {
	if x != nil {
		return x.Error
	}
	return AnnaError_NO_ERROR
}

func (x *KeyAddressResponse) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

// Serialization of last-write wins lattices.
type LWWValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The last-writer wins timestamp associated with this data.
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The actual data stored by this LWWValue.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LWWValue) Reset() {
	*x = LWWValue{}
	mi := &file_kvs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LWWValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LWWValue) ProtoMessage() {}

func (x *LWWValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LWWValue.ProtoReflect.Descriptor instead.
func (*LWWValue) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{5}
}

func (x *LWWValue) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LWWValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Serialization of unordered set lattices.
type SetValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An unordered set of values in this lattice.
	Values        [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValue) Reset() {
	*x = SetValue{}
	mi := &file_kvs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValue) ProtoMessage() {}

func (x *SetValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValue.ProtoReflect.Descriptor instead.
func (*SetValue) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{6}
}

func (x *SetValue) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// Serialization of a single-key causal lattice.
type SingleKeyCausalValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The vector clock for this key, which maps from unique client IDs to monotonically increasing integers.
	VectorClock map[string]uint32 `protobuf:"bytes,1,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// The set of values associated with this causal value. There will only be
	// more than one here if there are multiple causally concurrent updates.
	Values        [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleKeyCausalValue) Reset() {
	*x = SingleKeyCausalValue{}
	mi := &file_kvs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleKeyCausalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleKeyCausalValue) ProtoMessage() {}

func (x *SingleKeyCausalValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleKeyCausalValue.ProtoReflect.Descriptor instead.
func (*SingleKeyCausalValue) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{7}
}

func (x *SingleKeyCausalValue) GetVectorClock() map[string]uint32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *SingleKeyCausalValue) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// An individual multi-key causal lattice, along with its associated
// dependencies.
type MultiKeyCausalValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The vector clock associated with this particular key.
	VectorClock map[string]uint32 `protobuf:"bytes,1,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// The mapping from keys to vector clocks for each of the direct causal dependencies this key has.
	Dependencies []*shared.KeyVersion `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// The set of potentially causally concurrent values for this key.
	Values        [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiKeyCausalValue) Reset() {
	*x = MultiKeyCausalValue{}
	mi := &file_kvs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiKeyCausalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiKeyCausalValue) ProtoMessage() {}

func (x *MultiKeyCausalValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiKeyCausalValue.ProtoReflect.Descriptor instead.
func (*MultiKeyCausalValue) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{8}
}

func (x *MultiKeyCausalValue) GetVectorClock() map[string]uint32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *MultiKeyCausalValue) GetDependencies() []*shared.KeyVersion {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *MultiKeyCausalValue) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// Serialization of lowest-priority-wins lattices.
type PriorityValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The priority associated with this data
	Priority float64 `protobuf:"fixed64,1,opt,name=priority,proto3" json:"priority,omitempty"`
	// The actual data stored by this PriorityValue
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityValue) Reset() {
	*x = PriorityValue{}
	mi := &file_kvs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityValue) ProtoMessage() {}

func (x *PriorityValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityValue.ProtoReflect.Descriptor instead.
func (*PriorityValue) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{9}
}

func (x *PriorityValue) GetPriority() float64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PriorityValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A mapping from individual keys to the set of servers responsible for that key.
type KeyAddressResponse_KeyAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The specified key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The IPs of the set of servers responsible for this key.
	Ips           []string `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAddressResponse_KeyAddress) Reset() {
	*x = KeyAddressResponse_KeyAddress{}
	mi := &file_kvs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAddressResponse_KeyAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAddressResponse_KeyAddress) ProtoMessage() {}

func (x *KeyAddressResponse_KeyAddress) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAddressResponse_KeyAddress.ProtoReflect.Descriptor instead.
func (*KeyAddressResponse_KeyAddress) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{4, 0}
}

func (x *KeyAddressResponse_KeyAddress) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyAddressResponse_KeyAddress) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

var File_kvs_proto protoreflect.FileDescriptor

const file_kvs_proto_rawDesc = "" +
	"\n" +
	"\tkvs.proto\x12\x03kvs\x1a\fshared.proto\"\xdf\x01\n" +
	"\bKeyTuple\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\flattice_type\x18\x02 \x01(\x0e2\x10.kvs.LatticeTypeR\vlatticeType\x12$\n" +
	"\x05error\x18\x03 \x01(\x0e2\x0e.kvs.AnnaErrorR\x05error\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12,\n" +
	"\x12address_cache_size\x18\x05 \x01(\rR\x10addressCacheSize\x12\x1e\n" +
	"\n" +
	"invalidate\x18\x06 \x01(\bR\n" +
	"invalidate\"\xa3\x01\n" +
	"\n" +
	"KeyRequest\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.kvs.RequestTypeR\x04type\x12%\n" +
	"\x06tuples\x18\x02 \x03(\v2\r.kvs.KeyTupleR\x06tuples\x12)\n" +
	"\x10response_address\x18\x03 \x01(\tR\x0fresponseAddress\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xa1\x01\n" +
	"\vKeyResponse\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.kvs.RequestTypeR\x04type\x12%\n" +
	"\x06tuples\x18\x02 \x03(\v2\r.kvs.KeyTupleR\x06tuples\x12\x1f\n" +
	"\vresponse_id\x18\x03 \x01(\tR\n" +
	"responseId\x12$\n" +
	"\x05error\x18\x04 \x01(\x0e2\x0e.kvs.AnnaErrorR\x05error\"q\n" +
	"\x11KeyAddressRequest\x12)\n" +
	"\x10response_address\x18\x01 \x01(\tR\x0fresponseAddress\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xcf\x01\n" +
	"\x12KeyAddressResponse\x12@\n" +
	"\taddresses\x18\x01 \x03(\v2\".kvs.KeyAddressResponse.KeyAddressR\taddresses\x12$\n" +
	"\x05error\x18\x02 \x01(\x0e2\x0e.kvs.AnnaErrorR\x05error\x12\x1f\n" +
	"\vresponse_id\x18\x03 \x01(\tR\n" +
	"responseId\x1a0\n" +
	"\n" +
	"KeyAddress\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\">\n" +
	"\bLWWValue\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\"\n" +
	"\bSetValue\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"\xbd\x01\n" +
	"\x14SingleKeyCausalValue\x12M\n" +
	"\fvector_clock\x18\x01 \x03(\v2*.kvs.SingleKeyCausalValue.VectorClockEntryR\vvectorClock\x12\x16\n" +
	"\x06values\x18\x02 \x03(\fR\x06values\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x13MultiKeyCausalValue\x12L\n" +
	"\fvector_clock\x18\x01 \x03(\v2).kvs.MultiKeyCausalValue.VectorClockEntryR\vvectorClock\x126\n" +
	"\fdependencies\x18\x02 \x03(\v2\x12.shared.KeyVersionR\fdependencies\x12\x16\n" +
	"\x06values\x18\x03 \x03(\fR\x06values\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"A\n" +
	"\rPriorityValue\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\x01R\bpriority\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value*3\n" +
	"\vRequestType\x12\x12\n" +
	"\x0eRT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02*\xa9\x02\n" +
	"\vLatticeType\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03LWW\x10\x01\x12\a\n" +
	"\x03SET\x10\x02\x12\x11\n" +
	"\rSINGLE_CAUSAL\x10\x03\x12\x10\n" +
	"\fMULTI_CAUSAL\x10\x04\x12\x0f\n" +
	"\vORDERED_SET\x10\x05\x12\f\n" +
	"\bPRIORITY\x10\x06\x12\v\n" +
	"\aLWW_SET\x10\a\x12\x10\n" +
	"\fUNION_SCALAR\x10\b\x12\x13\n" +
	"\x0fLWW_ORDERED_SET\x10\t\x12\x10\n" +
	"\fPRIORITY_SET\x10\n" +
	"\x12\x18\n" +
	"\x14PRIORITY_ORDERED_SET\x10\v\x12\x0e\n" +
	"\n" +
	"CAUSAL_SET\x10\f\x12\x16\n" +
	"\x12CAUSAL_ORDERED_SET\x10\r\x12\x14\n" +
	"\x10MULTI_CAUSAL_SET\x10\x0e\x12\x1c\n" +
	"\x18MULTI_CAUSAL_ORDERED_SET\x10\x0f*b\n" +
	"\tAnnaError\x12\f\n" +
	"\bNO_ERROR\x10\x00\x12\v\n" +
	"\aKEY_DNE\x10\x01\x12\x10\n" +
	"\fWRONG_THREAD\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\x12\v\n" +
	"\aLATTICE\x10\x04\x12\x0e\n" +
	"\n" +
	"NO_SERVERS\x10\x05b\x06proto3"

var (
	file_kvs_proto_rawDescOnce sync.Once
	file_kvs_proto_rawDescData []byte
)

func file_kvs_proto_rawDescGZIP() []byte {
	file_kvs_proto_rawDescOnce.Do(func() {
		file_kvs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvs_proto_rawDesc), len(file_kvs_proto_rawDesc)))
	})
	return file_kvs_proto_rawDescData
}

var file_kvs_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_kvs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_kvs_proto_goTypes = []any{
	(RequestType)(0),                      // 0: kvs.RequestType
	(LatticeType)(0),                      // 1: kvs.LatticeType
	(AnnaError)(0),                        // 2: kvs.AnnaError
	(*KeyTuple)(nil),                      // 3: kvs.KeyTuple
	(*KeyRequest)(nil),                    // 4: kvs.KeyRequest
	(*KeyResponse)(nil),                   // 5: kvs.KeyResponse
	(*KeyAddressRequest)(nil),             // 6: kvs.KeyAddressRequest
	(*KeyAddressResponse)(nil),            // 7: kvs.KeyAddressResponse
	(*LWWValue)(nil),                      // 8: kvs.LWWValue
	(*SetValue)(nil),                      // 9: kvs.SetValue
	(*SingleKeyCausalValue)(nil),          // 10: kvs.SingleKeyCausalValue
	(*MultiKeyCausalValue)(nil),           // 11: kvs.MultiKeyCausalValue
	(*PriorityValue)(nil),                 // 12: kvs.PriorityValue
	(*KeyAddressResponse_KeyAddress)(nil), // 13: kvs.KeyAddressResponse.KeyAddress
	nil,                                   // 14: kvs.SingleKeyCausalValue.VectorClockEntry
	nil,                                   // 15: kvs.MultiKeyCausalValue.VectorClockEntry
	(*shared.KeyVersion)(nil),             // 16: shared.KeyVersion
}
var file_kvs_proto_depIdxs = []int32{
	1,  // 0: kvs.KeyTuple.lattice_type:type_name -> kvs.LatticeType
	2,  // 1: kvs.KeyTuple.error:type_name -> kvs.AnnaError
	0,  // 2: kvs.KeyRequest.type:type_name -> kvs.RequestType
	3,  // 3: kvs.KeyRequest.tuples:type_name -> kvs.KeyTuple
	0,  // 4: kvs.KeyResponse.type:type_name -> kvs.RequestType
	3,  // 5: kvs.KeyResponse.tuples:type_name -> kvs.KeyTuple
	2,  // 6: kvs.KeyResponse.error:type_name -> kvs.AnnaError
	13, // 7: kvs.KeyAddressResponse.addresses:type_name -> kvs.KeyAddressResponse.KeyAddress
	2,  // 8: kvs.KeyAddressResponse.error:type_name -> kvs.AnnaError
	14, // 9: kvs.SingleKeyCausalValue.vector_clock:type_name -> kvs.SingleKeyCausalValue.VectorClockEntry
	15, // 10: kvs.MultiKeyCausalValue.vector_clock:type_name -> kvs.MultiKeyCausalValue.VectorClockEntry
	16, // 11: kvs.MultiKeyCausalValue.dependencies:type_name -> shared.KeyVersion
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_kvs_proto_init() }
func file_kvs_proto_init() {
	if File_kvs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvs_proto_rawDesc), len(file_kvs_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kvs_proto_goTypes,
		DependencyIndexes: file_kvs_proto_depIdxs,
		EnumInfos:         file_kvs_proto_enumTypes,
		MessageInfos:      file_kvs_proto_msgTypes,
	}.Build()
	File_kvs_proto = out.File
	file_kvs_proto_goTypes = nil
	file_kvs_proto_depIdxs = nil
}
