[metadata]
name = anna
version = 0.1
author = Andrew Mackenzie
author_email = andrew@mackenzie-serres.net
description = CLI and python lib for ann KVS
#long_description = file: README.md
#long_description_content_type = text/markdown
url = https://github.com/andrewdavidmackenzie/anna/clients/python
classifiers =
    Programming Language :: Python :: 3
    Licence :: OSI Approved :: Apache v2
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.7
include_package_data = False
install_requires =
    pyzmq
    protobuf
    pyyaml

[options.entry_points]
console_scripts =
    anna-py = anna.cli:main
