# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: causal.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'causal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as shared__pb2
from . import kvs_pb2 as kvs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61usal.proto\x12\x06\x63\x61usal\x1a\x0cshared.proto\x1a\tkvs.proto\"J\n\x0b\x43\x61usalTuple\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x1d\n\x05\x65rror\x18\x03 \x01(\x0e\x32\x0e.kvs.AnnaError\"\xc4\x02\n\rCausalRequest\x12,\n\x0b\x63onsistency\x18\x01 \x01(\x0e\x32\x17.causal.ConsistencyType\x12\n\n\x02id\x18\x02 \x01(\t\x12#\n\x06tuples\x18\x03 \x03(\x0b\x32\x13.causal.CausalTuple\x12\x17\n\x0f\x66uture_read_set\x18\x04 \x03(\t\x12M\n\x15key_version_locations\x18\x05 \x03(\x0b\x32..causal.CausalRequest.KeyVersionLocationsEntry\x12\x18\n\x10response_address\x18\x06 \x01(\t\x1aR\n\x18KeyVersionLocationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.shared.KeyVersionList:\x02\x38\x01\"\x82\x01\n\x0e\x43\x61usalResponse\x12#\n\x06tuples\x18\x01 \x03(\x0b\x32\x13.causal.CausalTuple\x12!\n\x19key_version_query_address\x18\x02 \x01(\t\x12(\n\x0ckey_versions\x18\x03 \x03(\x0b\x32\x12.shared.KeyVersion\"G\n\x11KeyVersionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10response_address\x18\x02 \x01(\t\x12\x0c\n\x04keys\x18\x03 \x03(\t\"E\n\x12KeyVersionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12#\n\x06tuples\x18\x02 \x03(\x0b\x32\x13.causal.CausalTuple*4\n\x0f\x43onsistencyType\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\t\n\x05MULTI\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'causal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY']._loaded_options = None
  _globals['_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY']._serialized_options = b'8\001'
  _globals['_CONSISTENCYTYPE']._serialized_start=729
  _globals['_CONSISTENCYTYPE']._serialized_end=781
  _globals['_CAUSALTUPLE']._serialized_start=49
  _globals['_CAUSALTUPLE']._serialized_end=123
  _globals['_CAUSALREQUEST']._serialized_start=126
  _globals['_CAUSALREQUEST']._serialized_end=450
  _globals['_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY']._serialized_start=368
  _globals['_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY']._serialized_end=450
  _globals['_CAUSALRESPONSE']._serialized_start=453
  _globals['_CAUSALRESPONSE']._serialized_end=583
  _globals['_KEYVERSIONREQUEST']._serialized_start=585
  _globals['_KEYVERSIONREQUEST']._serialized_end=656
  _globals['_KEYVERSIONRESPONSE']._serialized_start=658
  _globals['_KEYVERSIONRESPONSE']._serialized_end=727
# @@protoc_insertion_point(module_scope)
