//  Copyright 2019 U.C. Berkeley RISE Lab
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An enum representing all the tiers the system supports -- currently, a
// memory tier and a disk-based tier.
type Tier int32

const (
	Tier_TIER_UNSPECIFIED Tier = 0
	// The value for the memory tier.
	Tier_MEMORY Tier = 1
	// The value for the disk-based tier.
	Tier_DISK Tier = 2
	// The value for the routing tier.
	Tier_ROUTING Tier = 3
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "MEMORY",
		2: "DISK",
		3: "ROUTING",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"MEMORY":           1,
		"DISK":             2,
		"ROUTING":          3,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

// A message to capture the periodic reporting of each server thread's local
// statistics; these are aggregated by the monitoring system.
type ServerThreadStatistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What percentage of the server thread's storage capacity is being consumed.
	StorageConsumption uint64 `protobuf:"varint,1,opt,name=storage_consumption,json=storageConsumption,proto3" json:"storage_consumption,omitempty"`
	// What percentage of the server thread's compute capacity is being consumed.
	Occupancy float64 `protobuf:"fixed64,2,opt,name=occupancy,proto3" json:"occupancy,omitempty"`
	// The server thread's reporting epoch.
	Epoch uint32 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// How many key accesses were serviced during this epoch.
	AccessCount   uint32 `protobuf:"varint,4,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerThreadStatistics) Reset() {
	*x = ServerThreadStatistics{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerThreadStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerThreadStatistics) ProtoMessage() {}

func (x *ServerThreadStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerThreadStatistics.ProtoReflect.Descriptor instead.
func (*ServerThreadStatistics) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ServerThreadStatistics) GetStorageConsumption() uint64 {
	if x != nil {
		return x.StorageConsumption
	}
	return 0
}

func (x *ServerThreadStatistics) GetOccupancy() float64 {
	if x != nil {
		return x.Occupancy
	}
	return 0
}

func (x *ServerThreadStatistics) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ServerThreadStatistics) GetAccessCount() uint32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

// A message to capture the access frequencies of individual keys for a
// particular server thread.
type KeyAccessData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of all the key access frequencies tracked during this epoch.
	Keys          []*KeyAccessData_KeyCount `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAccessData) Reset() {
	*x = KeyAccessData{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAccessData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAccessData) ProtoMessage() {}

func (x *KeyAccessData) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAccessData.ProtoReflect.Descriptor instead.
func (*KeyAccessData) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *KeyAccessData) GetKeys() []*KeyAccessData_KeyCount {
	if x != nil {
		return x.Keys
	}
	return nil
}

// A message to track which physical servers are a part of which Anna
// membership (memory, disk) tier.
type ClusterMembership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of all tiers in the system.
	Tiers         []*ClusterMembership_TierMembership `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMembership) Reset() {
	*x = ClusterMembership{}
	mi := &file_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMembership) ProtoMessage() {}

func (x *ClusterMembership) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMembership.ProtoReflect.Descriptor instead.
func (*ClusterMembership) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterMembership) GetTiers() []*ClusterMembership_TierMembership {
	if x != nil {
		return x.Tiers
	}
	return nil
}

// A message to track metadata about how large each key in the system is.
type KeySizeData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of key size metadata tuples being reported.
	KeySizes      []*KeySizeData_KeySize `protobuf:"bytes,1,rep,name=key_sizes,json=keySizes,proto3" json:"key_sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySizeData) Reset() {
	*x = KeySizeData{}
	mi := &file_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySizeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySizeData) ProtoMessage() {}

func (x *KeySizeData) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySizeData.ProtoReflect.Descriptor instead.
func (*KeySizeData) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *KeySizeData) GetKeySizes() []*KeySizeData_KeySize {
	if x != nil {
		return x.KeySizes
	}
	return nil
}

// A message that captures the replication factor for an individual key.
type ReplicationFactor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the key whose replication factor is being changed.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// A set of mappings from individual tiers (MEMORY, DISK -- see Tier enum)
	// to the cross-machine replication factor at that tier.
	Global []*ReplicationFactor_ReplicationValue `protobuf:"bytes,2,rep,name=global,proto3" json:"global,omitempty"`
	// A set of mappings from individual tiers (MEMORY, DISK -- see Tier enum)
	// to the intra-machine replication factor at that tier.
	Local         []*ReplicationFactor_ReplicationValue `protobuf:"bytes,3,rep,name=local,proto3" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationFactor) Reset() {
	*x = ReplicationFactor{}
	mi := &file_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationFactor) ProtoMessage() {}

func (x *ReplicationFactor) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationFactor.ProtoReflect.Descriptor instead.
func (*ReplicationFactor) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicationFactor) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicationFactor) GetGlobal() []*ReplicationFactor_ReplicationValue {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ReplicationFactor) GetLocal() []*ReplicationFactor_ReplicationValue {
	if x != nil {
		return x.Local
	}
	return nil
}

// A message to propagate changes to a set of keys' replication factors.
type ReplicationFactorUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of replication factor updates being sent.
	Updates       []*ReplicationFactor `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationFactorUpdate) Reset() {
	*x = ReplicationFactorUpdate{}
	mi := &file_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationFactorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationFactorUpdate) ProtoMessage() {}

func (x *ReplicationFactorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationFactorUpdate.ProtoReflect.Descriptor instead.
func (*ReplicationFactorUpdate) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicationFactorUpdate) GetUpdates() []*ReplicationFactor {
	if x != nil {
		return x.Updates
	}
	return nil
}

// Cluster topology information published as ANNA_METADATA|cluster_topology
// so clients can discover thread counts at runtime.
type ClusterTopology struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of routing threads per routing node.
	RoutingThreadCount uint32 `protobuf:"varint,1,opt,name=routing_thread_count,json=routingThreadCount,proto3" json:"routing_thread_count,omitempty"`
	// Number of memory-tier threads per KVS node.
	MemoryThreadCount uint32 `protobuf:"varint,2,opt,name=memory_thread_count,json=memoryThreadCount,proto3" json:"memory_thread_count,omitempty"`
	// Number of disk-tier threads per KVS node.
	DiskThreadCount uint32 `protobuf:"varint,3,opt,name=disk_thread_count,json=diskThreadCount,proto3" json:"disk_thread_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterTopology) Reset() {
	*x = ClusterTopology{}
	mi := &file_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterTopology) ProtoMessage() {}

func (x *ClusterTopology) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterTopology.ProtoReflect.Descriptor instead.
func (*ClusterTopology) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterTopology) GetRoutingThreadCount() uint32 {
	if x != nil {
		return x.RoutingThreadCount
	}
	return 0
}

func (x *ClusterTopology) GetMemoryThreadCount() uint32 {
	if x != nil {
		return x.MemoryThreadCount
	}
	return 0
}

func (x *ClusterTopology) GetDiskThreadCount() uint32 {
	if x != nil {
		return x.DiskThreadCount
	}
	return 0
}

// A mapping from an individual key to its access count.
type KeyAccessData_KeyCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key being tracked.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The number of times this key was accessed during this epoch.
	AccessCount   uint32 `protobuf:"varint,2,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAccessData_KeyCount) Reset() {
	*x = KeyAccessData_KeyCount{}
	mi := &file_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAccessData_KeyCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAccessData_KeyCount) ProtoMessage() {}

func (x *KeyAccessData_KeyCount) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAccessData_KeyCount.ProtoReflect.Descriptor instead.
func (*KeyAccessData_KeyCount) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1, 0}
}

func (x *KeyAccessData_KeyCount) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyAccessData_KeyCount) GetAccessCount() uint32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

// The representation the servers comprising an individual tier.
type ClusterMembership_TierMembership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Tier represented by this message -- either MEMORY or DISK.
	TierId Tier `protobuf:"varint,1,opt,name=tier_id,json=tierId,proto3,enum=Tier" json:"tier_id,omitempty"`
	// The list of servers in this tier.
	Servers       []*ClusterMembership_TierMembership_Server `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMembership_TierMembership) Reset() {
	*x = ClusterMembership_TierMembership{}
	mi := &file_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMembership_TierMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMembership_TierMembership) ProtoMessage() {}

func (x *ClusterMembership_TierMembership) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMembership_TierMembership.ProtoReflect.Descriptor instead.
func (*ClusterMembership_TierMembership) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ClusterMembership_TierMembership) GetTierId() Tier {
	if x != nil {
		return x.TierId
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *ClusterMembership_TierMembership) GetServers() []*ClusterMembership_TierMembership_Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

// The IP addresses for an individual server -- the private/public IP
// distinction is specific to EC2-based deployments.
type ClusterMembership_TierMembership_Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public IP address for a server.
	PublicIp string `protobuf:"bytes,1,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	// The private IP address for a server.
	PrivateIp     string `protobuf:"bytes,2,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMembership_TierMembership_Server) Reset() {
	*x = ClusterMembership_TierMembership_Server{}
	mi := &file_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMembership_TierMembership_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMembership_TierMembership_Server) ProtoMessage() {}

func (x *ClusterMembership_TierMembership_Server) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMembership_TierMembership_Server.ProtoReflect.Descriptor instead.
func (*ClusterMembership_TierMembership_Server) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ClusterMembership_TierMembership_Server) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *ClusterMembership_TierMembership_Server) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

// The size metadata for an individual key.
type KeySizeData_KeySize struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key for which size metadata is being reported.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The size of the above key.
	Size          uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySizeData_KeySize) Reset() {
	*x = KeySizeData_KeySize{}
	mi := &file_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySizeData_KeySize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySizeData_KeySize) ProtoMessage() {}

func (x *KeySizeData_KeySize) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySizeData_KeySize.ProtoReflect.Descriptor instead.
func (*KeySizeData_KeySize) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{3, 0}
}

func (x *KeySizeData_KeySize) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeySizeData_KeySize) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// A message representing the replication level for a single key at a
// single tier.
type ReplicationFactor_ReplicationValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tier represented by this message.
	Tier Tier `protobuf:"varint,1,opt,name=tier,proto3,enum=Tier" json:"tier,omitempty"`
	// The replication level at this particular tier for this particular key.
	Value         uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationFactor_ReplicationValue) Reset() {
	*x = ReplicationFactor_ReplicationValue{}
	mi := &file_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationFactor_ReplicationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationFactor_ReplicationValue) ProtoMessage() {}

func (x *ReplicationFactor_ReplicationValue) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationFactor_ReplicationValue.ProtoReflect.Descriptor instead.
func (*ReplicationFactor_ReplicationValue) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ReplicationFactor_ReplicationValue) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *ReplicationFactor_ReplicationValue) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\"\xa0\x01\n" +
	"\x16ServerThreadStatistics\x12/\n" +
	"\x13storage_consumption\x18\x01 \x01(\x04R\x12storageConsumption\x12\x1c\n" +
	"\toccupancy\x18\x02 \x01(\x01R\toccupancy\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x12!\n" +
	"\faccess_count\x18\x04 \x01(\rR\vaccessCount\"}\n" +
	"\rKeyAccessData\x12+\n" +
	"\x04keys\x18\x01 \x03(\v2\x17.KeyAccessData.KeyCountR\x04keys\x1a?\n" +
	"\bKeyCount\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\faccess_count\x18\x02 \x01(\rR\vaccessCount\"\x89\x02\n" +
	"\x11ClusterMembership\x127\n" +
	"\x05tiers\x18\x01 \x03(\v2!.ClusterMembership.TierMembershipR\x05tiers\x1a\xba\x01\n" +
	"\x0eTierMembership\x12\x1e\n" +
	"\atier_id\x18\x01 \x01(\x0e2\x05.TierR\x06tierId\x12B\n" +
	"\aservers\x18\x02 \x03(\v2(.ClusterMembership.TierMembership.ServerR\aservers\x1aD\n" +
	"\x06Server\x12\x1b\n" +
	"\tpublic_ip\x18\x01 \x01(\tR\bpublicIp\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x02 \x01(\tR\tprivateIp\"q\n" +
	"\vKeySizeData\x121\n" +
	"\tkey_sizes\x18\x01 \x03(\v2\x14.KeySizeData.KeySizeR\bkeySizes\x1a/\n" +
	"\aKeySize\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\xe2\x01\n" +
	"\x11ReplicationFactor\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x06global\x18\x02 \x03(\v2#.ReplicationFactor.ReplicationValueR\x06global\x129\n" +
	"\x05local\x18\x03 \x03(\v2#.ReplicationFactor.ReplicationValueR\x05local\x1aC\n" +
	"\x10ReplicationValue\x12\x19\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x05.TierR\x04tier\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\"G\n" +
	"\x17ReplicationFactorUpdate\x12,\n" +
	"\aupdates\x18\x01 \x03(\v2\x12.ReplicationFactorR\aupdates\"\x9f\x01\n" +
	"\x0fClusterTopology\x120\n" +
	"\x14routing_thread_count\x18\x01 \x01(\rR\x12routingThreadCount\x12.\n" +
	"\x13memory_thread_count\x18\x02 \x01(\rR\x11memoryThreadCount\x12*\n" +
	"\x11disk_thread_count\x18\x03 \x01(\rR\x0fdiskThreadCount*?\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06MEMORY\x10\x01\x12\b\n" +
	"\x04DISK\x10\x02\x12\v\n" +
	"\aROUTING\x10\x03b\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_metadata_proto_goTypes = []any{
	(Tier)(0),                                       // 0: Tier
	(*ServerThreadStatistics)(nil),                  // 1: ServerThreadStatistics
	(*KeyAccessData)(nil),                           // 2: KeyAccessData
	(*ClusterMembership)(nil),                       // 3: ClusterMembership
	(*KeySizeData)(nil),                             // 4: KeySizeData
	(*ReplicationFactor)(nil),                       // 5: ReplicationFactor
	(*ReplicationFactorUpdate)(nil),                 // 6: ReplicationFactorUpdate
	(*ClusterTopology)(nil),                         // 7: ClusterTopology
	(*KeyAccessData_KeyCount)(nil),                  // 8: KeyAccessData.KeyCount
	(*ClusterMembership_TierMembership)(nil),        // 9: ClusterMembership.TierMembership
	(*ClusterMembership_TierMembership_Server)(nil), // 10: ClusterMembership.TierMembership.Server
	(*KeySizeData_KeySize)(nil),                     // 11: KeySizeData.KeySize
	(*ReplicationFactor_ReplicationValue)(nil),      // 12: ReplicationFactor.ReplicationValue
}
var file_metadata_proto_depIdxs = []int32{
	8,  // 0: KeyAccessData.keys:type_name -> KeyAccessData.KeyCount
	9,  // 1: ClusterMembership.tiers:type_name -> ClusterMembership.TierMembership
	11, // 2: KeySizeData.key_sizes:type_name -> KeySizeData.KeySize
	12, // 3: ReplicationFactor.global:type_name -> ReplicationFactor.ReplicationValue
	12, // 4: ReplicationFactor.local:type_name -> ReplicationFactor.ReplicationValue
	5,  // 5: ReplicationFactorUpdate.updates:type_name -> ReplicationFactor
	0,  // 6: ClusterMembership.TierMembership.tier_id:type_name -> Tier
	10, // 7: ClusterMembership.TierMembership.servers:type_name -> ClusterMembership.TierMembership.Server
	0,  // 8: ReplicationFactor.ReplicationValue.tier:type_name -> Tier
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		EnumInfos:         file_metadata_proto_enumTypes,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
