//! Re-exports of protobuf types generated by prost.
//!
//! All `.proto` files live in `server/protobuf/` and are compiled
//! by `build.rs`. The generated modules mirror the protobuf package names.

#[allow(warnings, missing_docs)]
pub mod shared {
    include!(concat!(env!("OUT_DIR"), "/shared.rs"));
}

#[allow(warnings, missing_docs)]
pub mod kvs {
    include!(concat!(env!("OUT_DIR"), "/kvs.rs"));
}

#[allow(warnings, missing_docs)]
pub mod causal {
    include!(concat!(env!("OUT_DIR"), "/causal.rs"));
}

// metadata.proto and benchmark.proto have no package declaration,
// so prost merges them into _.rs.
#[allow(warnings, missing_docs)]
pub mod metadata {
    include!(concat!(env!("OUT_DIR"), "/_.rs"));
}
