name: Build-test-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # Build every day at 5PM UTC
    - cron: '0 17 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest ]
          rust: [ stable ]

    steps:
    - uses: actions/checkout@v3

    - name: InstallDependencies
      if: matrix.os != 'windows-latest'
      run: make dependencies

    - name: InstallDependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install make cmake --no-progress -y
        cargo install mdbook grcov
        rustup component add llvm-tools-preview

    - name: ConfigureCoverage
      if: matrix.os == 'macos-latest'
      run: |
        echo RUSTFLAGS="-C instrument-coverage" >> "$GITHUB_ENV"
        echo LLVM_PROFILE_FILE="flow-%p-%m.profraw" >> "$GITHUB_ENV"

    - name: clippy
      run: make clippy

    - name: build
      run: make build

    - name: test
      run: make test

    - uses: codecov/codecov-action@v2
      if: matrix.os == 'macos-latest'
      with:
        files: rust_workspace.info server/cpp/build/server.info clients/cpp/build/client.info

    - name: docs
      if: matrix.os == 'macos-latest'
      run: make docs

    - name: DeployDocsToGHPages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: matrix.os == 'macos-latest' && github.ref == 'refs/heads/master'
      with:
        branch: gh-pages
        folder: target/html