name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # Build every day at 5PM UTC
    - cron: '0 17 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ macos-latest, ubuntu-latest ]
          rust: [ stable ]

    steps:
    - uses: actions/checkout@v2

    - name: InstallLinuxDependencies
      if: matrix.os == 'ubuntu-latest'
      run: make linux_dependencies

    - name: InstallMacDependencies
      if: matrix.os == 'macos-latest'
      run: make mac_dependencies

    - name: ConfigureCoverage
      if: matrix.os == 'ubuntu-latest'
      run: |
        make configure_coverage
        echo RUSTFLAGS="-C instrument-coverage" >> "$GITHUB_ENV"
        echo LLVM_PROFILE_FILE="flow-%p-%m.profraw" >> "$GITHUB_ENV"

    - name: clippy
      run: make clippy

    - name: build
      run: make build

    - name: test
      run: make test

    - name: docs
      if: matrix.os == 'ubuntu-latest'
      run: make docs

    - name: UploadCoverage
      if: matrix.os == 'ubuntu-latest'
      run: make upload_coverage

    - name: DeployDocsToGHPages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
      with:
        branch: gh-pages
        folder: target/html